apiVersion: apps/v1
kind: Deployment
metadata:
  name: rm10519875-mongodb-s
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: rm10519875-mongodb-s
  template:
    metadata:
      labels:
        deployment-name: rm10519875-mongodb-s
    spec:
      containers:
        - name: rm10519875-mongodb-s
          image: mongo
          env:
            - name: MONGO_INITDB_DATABASE
              value: database
          ports:
            - containerPort: 27017 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: rm10519875-mongodb-s-cluster-service
  name: rm10519875-mongodb-s-cluster-service-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - name: rm10519875-mongodb-s-loadbalancer-service-port
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    deployment-name: rm10519875-api-s-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 10519875-api-s  
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: 10519875-api-s
  template:
    metadata:
      labels:
        deployment-name: 10519875-api-s
    spec:
      containers:
      - name: 10519875-api-s
        image: cab8it148.azurecr.io/10519875-api-s
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: rm10519875-api-s-cluster-service
  name: rm10519875-api-s-cluster-service-loadbalancer
spec:
  type: LoadBalancer
  ports:
  - name: rm10519875-api-s-loadbalancer
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    deployment-name: 10519875-api-s